[package]
name = "maskraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "proto"]

[dependencies]
log = "0.4.20"
proto = { path = "proto" }
simple_logger = "4.3.3"
